### PR TITLE
Update apm-mutating-webhook.asciidoc

### PR DESCRIPTION
**Pull request by estolfo**
The .NET attacher is not GA and won't be until after 8.12.

I'm not sure if the "tech preview" message at the top will be removed for 8.12. If so, then we should mark only the .NET attacher as tech preview.

### CODE REVIEW

**Comment by bmorelli25** [comment]
[`e9067c6`](https://github.com/elastic/apm-k8s-attacher/pull/85/commits/e9067c6db722cf7d6898a8fe59b144f935a5e284) removes the preview admonition from the top of the page and adds an inline preview to the .NET agent line.
Screenshot 2024-01-02 at 1 35 10 PM

**Review by bmorelli25 — APPROVED** [review]
I'm not sure how to fix the failing ci check.

**Comment by estolfo** [comment]
It looks like it's checking the year in the NOTICE.txt to make sure it matches the current one. So I'll update it to 2024.

**Comment by estolfo** [comment]
@bmorelli25 I fixed that failing test, if you want to rebase

**Comment by bmorelli25** [comment]
Checks are green. It looks like my approval isn't good enough to merge this PR.

**Review by jackshirazi — APPROVED** [review]

**Pull request merged**
