### PR TITLE
Fixed wrong link URL, and added some clarity to various points

### PR DESCRIPTION
**Pull request by jackshirazi**

### CODE REVIEW

**Review by gregkalapos — APPROVED** [review]

**Comment by jackshirazi** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by jackshirazi** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by jackshirazi** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by jackshirazi** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
